import 'dart:convert';
import 'dart:io';

import '../models/agent_status.dart';

class AgentConnection {
  AgentConnection({
    required this.name,
    required this.baseUri,
    required this.token,
  });

  final String name;
  final Uri baseUri;
  final String token;

  static AgentConnection parse({
    required String name,
    required String serverUrl,
    required String token,
  }) {
    final uri = Uri.tryParse(serverUrl.trim());
    if (uri == null || !uri.hasScheme || uri.host.isEmpty) {
      throw const FormatException(
        'Enter a complete server URL, such as https://server.example.com:7443.',
      );
    }
    if (uri.scheme != 'https' && !_isLoopback(uri)) {
      throw const FormatException(
        'Remote servers must use HTTPS. Plain HTTP is allowed only for localhost development.',
      );
    }
    if (uri.hasQuery ||
        uri.hasFragment ||
        (uri.path.isNotEmpty && uri.path != '/')) {
      throw const FormatException(
        'The server URL cannot include a path, query, or fragment.',
      );
    }
    if (token.trim().isEmpty) {
      throw const FormatException(
        'Enter the agent token generated by the server.',
      );
    }
    return AgentConnection(
      name: name.trim().isEmpty ? uri.host : name.trim(),
      baseUri: uri.replace(path: ''),
      token: token.trim(),
    );
  }

  static bool _isLoopback(Uri uri) {
    return uri.host == 'localhost' ||
        uri.host == '127.0.0.1' ||
        uri.host == '::1';
  }
}

class AgentClient {
  AgentClient({HttpClient? httpClient})
    : _httpClient = httpClient ?? HttpClient();

  final HttpClient _httpClient;

  Future<AgentStatus> fetchStatus(AgentConnection connection) async {
    final request = await _httpClient
        .getUrl(connection.baseUri.resolve('/v1/status'))
        .timeout(const Duration(seconds: 10));
    request.headers.set(
      HttpHeaders.authorizationHeader,
      'Bearer ${connection.token}',
    );
    request.headers.set(HttpHeaders.acceptHeader, ContentType.json.mimeType);
    request.headers.set('X-EasyPrivacy-Client', 'app/0.1.0');

    final response = await request.close().timeout(const Duration(seconds: 10));
    final body = await utf8.decoder.bind(response).join();
    if (response.statusCode == HttpStatus.unauthorized) {
      throw const AgentException('The server rejected this device token.');
    }
    if (response.statusCode != HttpStatus.ok) {
      throw AgentException(
        'The server returned ${response.statusCode}${body.isEmpty ? '.' : ': $body'}',
      );
    }

    final decoded = jsonDecode(body);
    if (decoded is! Map) {
      throw const AgentException(
        'The server returned an invalid status response.',
      );
    }
    return AgentStatus.fromJson(
      decoded.map((key, value) => MapEntry(key.toString(), value)),
    );
  }

  void close() => _httpClient.close(force: true);
}

class AgentException implements Exception {
  const AgentException(this.message);

  final String message;

  @override
  String toString() => message;
}
